# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Aroha_SwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Aroha_SwiftUI
  pod 'ARCL'
  pod 'CocoaLumberjack/Swift'
  target 'Aroha_SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Aroha_SwiftUIUITests' do
    # Pods for testing
  end

end
